2017-05-05 19:16:43,726 [26] DEBUG ApplicationLogger [(null)] - 日志服务开启成功！
2017-05-05 19:16:54,395 [6] DEBUG ApplicationLogger [(null)] - PoController无参数构造函数初始化！
2017-05-05 19:18:41,332 [1] DEBUG ApplicationLogger [(null)] - 日志服务开启成功！
2017-05-05 19:19:13,062 [10] DEBUG ApplicationLogger [(null)] - PoController无参数构造函数初始化！
2017-05-05 19:21:13,735 [15] DEBUG ApplicationLogger [(null)] - PoController无参数构造函数初始化！
2017-05-05 19:22:42,096 [1] DEBUG ApplicationLogger [(null)] - 日志服务开启成功！
2017-05-05 19:24:22,160 [5] DEBUG ApplicationLogger [(null)] - PoController无参数构造函数初始化！
2017-05-05 19:25:13,890 [1] DEBUG ApplicationLogger [(null)] - 日志服务开启成功！
2017-05-05 19:25:14,191 [11] DEBUG ApplicationLogger [(null)] - PoController无参数构造函数初始化！
2017-05-05 19:25:14,461 [11] DEBUG ApplicationLogger [(null)] - PoServicey一个参数构造函数
2017-05-05 19:25:14,465 [11] DEBUG ApplicationLogger [(null)] - 初始化PoBusiness
2017-05-05 19:27:53,744 [1] DEBUG ApplicationLogger [(null)] - 日志服务开启成功！
2017-05-05 19:27:54,011 [5] DEBUG ApplicationLogger [(null)] - PoController无参数构造函数初始化！
2017-05-05 19:27:54,272 [5] DEBUG ApplicationLogger [(null)] - PoServicey一个参数构造函数
2017-05-05 19:27:54,277 [5] DEBUG ApplicationLogger [(null)] - 一个参数构造函数初始化PoRepository
2017-05-05 19:27:54,861 [5] ERROR ApplicationLogger [(null)] - 执行请求时出现异常！错误信息：Mapper not initialized. Call Initialize with appropriate configuration. If you are trying to use mapper instances through a container or otherwise, make sure you do not have any calls to the static Mapper.Map methods, and if you're using ProjectTo or UseAsDataSource extension methods, make sure you pass in the appropriate IConfigurationProvider instance.，请求参数：
System.InvalidOperationException: Mapper not initialized. Call Initialize with appropriate configuration. If you are trying to use mapper instances through a container or otherwise, make sure you do not have any calls to the static Mapper.Map methods, and if you're using ProjectTo or UseAsDataSource extension methods, make sure you pass in the appropriate IConfigurationProvider instance.
   在 AutoMapper.Mapper.get_Configuration()
   在 AutoMapper.QueryableExtensions.Extensions.ProjectTo[TDestination](IQueryable source, Expression`1[] membersToExpand)
   在 Infrastructure.Repositories.Purchase.PoRepository.GetList(Expression`1 predicate) 位置 E:\study\WebApi\Business\Repositories\Purchase\PoRepository.cs:行号 23
   在 WebApi.Controllers.Purchase.PoController.Search(Paramater paramater) 位置 E:\study\WebApi\WebApi\Controllers\Purchase\PoController.cs:行号 45
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2017-05-05 19:28:13,224 [17] DEBUG ApplicationLogger [(null)] - PoController无参数构造函数初始化！
2017-05-05 19:28:13,230 [17] DEBUG ApplicationLogger [(null)] - PoServicey一个参数构造函数
2017-05-05 19:28:13,231 [17] DEBUG ApplicationLogger [(null)] - 一个参数构造函数初始化PoRepository
2017-05-05 19:28:13,234 [17] ERROR ApplicationLogger [(null)] - 执行请求时出现异常！错误信息：Mapper not initialized. Call Initialize with appropriate configuration. If you are trying to use mapper instances through a container or otherwise, make sure you do not have any calls to the static Mapper.Map methods, and if you're using ProjectTo or UseAsDataSource extension methods, make sure you pass in the appropriate IConfigurationProvider instance.，请求参数：
System.InvalidOperationException: Mapper not initialized. Call Initialize with appropriate configuration. If you are trying to use mapper instances through a container or otherwise, make sure you do not have any calls to the static Mapper.Map methods, and if you're using ProjectTo or UseAsDataSource extension methods, make sure you pass in the appropriate IConfigurationProvider instance.
   在 AutoMapper.Mapper.get_Configuration()
   在 AutoMapper.QueryableExtensions.Extensions.ProjectTo[TDestination](IQueryable source, Expression`1[] membersToExpand)
   在 Infrastructure.Repositories.Purchase.PoRepository.GetList(Expression`1 predicate) 位置 E:\study\WebApi\Business\Repositories\Purchase\PoRepository.cs:行号 23
   在 WebApi.Controllers.Purchase.PoController.Search(Paramater paramater) 位置 E:\study\WebApi\WebApi\Controllers\Purchase\PoController.cs:行号 45
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2017-05-05 19:28:42,993 [15] DEBUG ApplicationLogger [(null)] - PoController无参数构造函数初始化！
2017-05-05 19:28:42,993 [15] DEBUG ApplicationLogger [(null)] - PoServicey一个参数构造函数
2017-05-05 19:28:42,994 [15] DEBUG ApplicationLogger [(null)] - 一个参数构造函数初始化PoRepository
2017-05-05 19:28:42,996 [15] ERROR ApplicationLogger [(null)] - 执行请求时出现异常！错误信息：Mapper not initialized. Call Initialize with appropriate configuration. If you are trying to use mapper instances through a container or otherwise, make sure you do not have any calls to the static Mapper.Map methods, and if you're using ProjectTo or UseAsDataSource extension methods, make sure you pass in the appropriate IConfigurationProvider instance.，请求参数：
System.InvalidOperationException: Mapper not initialized. Call Initialize with appropriate configuration. If you are trying to use mapper instances through a container or otherwise, make sure you do not have any calls to the static Mapper.Map methods, and if you're using ProjectTo or UseAsDataSource extension methods, make sure you pass in the appropriate IConfigurationProvider instance.
   在 AutoMapper.Mapper.get_Configuration()
   在 AutoMapper.QueryableExtensions.Extensions.ProjectTo[TDestination](IQueryable source, Expression`1[] membersToExpand)
   在 Infrastructure.Repositories.Purchase.PoRepository.GetList(Expression`1 predicate) 位置 E:\study\WebApi\Business\Repositories\Purchase\PoRepository.cs:行号 23
   在 WebApi.Controllers.Purchase.PoController.Search(Paramater paramater) 位置 E:\study\WebApi\WebApi\Controllers\Purchase\PoController.cs:行号 45
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2017-05-05 19:31:23,950 [22] DEBUG ApplicationLogger [(null)] - 日志服务开启成功！
2017-05-05 19:31:37,177 [3] DEBUG ApplicationLogger [(null)] - PoController无参数构造函数初始化！
2017-05-05 19:31:37,501 [3] DEBUG ApplicationLogger [(null)] - PoServicey一个参数构造函数
2017-05-05 19:31:37,988 [3] DEBUG ApplicationLogger [(null)] - 一个参数构造函数初始化PoRepository
2017-05-05 19:31:38,236 [3] ERROR ApplicationLogger [(null)] - 执行请求时出现异常！错误信息：Missing map from IInfrastructure.Models.Purchase.Po to IInfrastructure.Models.Purchase.Po. Create using Mapper.CreateMap<Po, Po>.，请求参数：
System.InvalidOperationException: Missing map from IInfrastructure.Models.Purchase.Po to IInfrastructure.Models.Purchase.Po. Create using Mapper.CreateMap<Po, Po>.
   在 AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(ExpressionRequest request, Expression instanceParameter, IDictionary`2 typePairCount)
   在 AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(ExpressionRequest request, IDictionary`2 typePairCount)
   在 AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(ExpressionRequest request)
   在 AutoMapper.LockingConcurrentDictionary`2.<>c__DisplayClass2_1.<.ctor>b__1()
   在 System.Lazy`1.CreateValue()
   在 System.Lazy`1.LazyInitValue()
   在 System.Lazy`1.get_Value()
   在 AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(Type sourceType, Type destinationType, IDictionary`2 parameters, MemberInfo[] membersToExpand)
   在 AutoMapper.QueryableExtensions.ProjectionExpression.To[TResult](IDictionary`2 parameters, IEnumerable`1 memberPathsToExpand)
   在 AutoMapper.QueryableExtensions.ProjectionExpression.To[TResult](Object parameters, Expression`1[] membersToExpand)
   在 AutoMapper.QueryableExtensions.Extensions.ProjectTo[TDestination](IQueryable source, IConfigurationProvider configuration, Object parameters, Expression`1[] membersToExpand)
   在 AutoMapper.QueryableExtensions.Extensions.ProjectTo[TDestination](IQueryable source, Expression`1[] membersToExpand)
   在 Infrastructure.Repositories.Purchase.PoRepository.GetList(Expression`1 predicate) 位置 E:\study\WebApi\Business\Repositories\Purchase\PoRepository.cs:行号 27
   在 WebApi.Controllers.Purchase.PoController.Search(Paramater paramater) 位置 E:\study\WebApi\WebApi\Controllers\Purchase\PoController.cs:行号 45
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2017-05-05 19:37:48,062 [1] DEBUG ApplicationLogger [(null)] - 日志服务开启成功！
2017-05-05 19:37:59,469 [20] DEBUG ApplicationLogger [(null)] - PoController无参数构造函数初始化！
2017-05-05 19:37:59,755 [20] DEBUG ApplicationLogger [(null)] - PoServicey一个参数构造函数
2017-05-05 19:38:00,144 [20] DEBUG ApplicationLogger [(null)] - 一个参数构造函数初始化PoRepository
2017-05-09 15:16:06,143 [1] DEBUG ApplicationLogger [(null)] - 日志服务开启成功！
2017-05-09 15:30:38,315 [1] DEBUG ApplicationLogger [(null)] - 日志服务开启成功！
2017-05-09 15:31:47,518 [12] DEBUG ApplicationLogger [(null)] - PoController无参数构造函数初始化！
2017-05-09 15:31:47,604 [12] DEBUG ApplicationLogger [(null)] - PoServicey一个参数构造函数
2017-05-09 15:31:47,921 [12] DEBUG ApplicationLogger [(null)] - 一个参数构造函数初始化PoRepository
2017-05-13 16:40:00,038 [1] DEBUG ApplicationLogger [(null)] - 日志服务开启成功！
2017-05-17 16:07:13,476 [1] DEBUG ApplicationLogger [(null)] - 日志服务开启成功！
2017-05-17 16:08:05,314 [7] DEBUG ApplicationLogger [(null)] - PoController无参数构造函数初始化！
2017-05-25 15:11:15,098 [1] DEBUG ApplicationLogger [(null)] - 日志服务开启成功！
2017-05-25 15:11:46,846 [8] DEBUG ApplicationLogger [(null)] - PoController无参数构造函数初始化！
2017-05-25 15:11:59,590 [10] DEBUG ApplicationLogger [(null)] - PoController无参数构造函数初始化！
2017-09-05 15:08:51,375 [1] DEBUG ApplicationLogger [(null)] - 日志服务开启成功！
2017-09-05 15:10:15,715 [11] DEBUG ApplicationLogger [(null)] - PoController无参数构造函数初始化！
2017-09-05 15:10:49,886 [5] DEBUG ApplicationLogger [(null)] - PoController无参数构造函数初始化！
2017-09-05 15:11:10,404 [13] DEBUG ApplicationLogger [(null)] - PoController无参数构造函数初始化！
2017-09-05 15:11:44,517 [8] DEBUG ApplicationLogger [(null)] - PoController无参数构造函数初始化！
2017-11-06 14:56:24,477 [1] DEBUG ApplicationLogger [(null)] - 日志服务开启成功！
2017-11-06 14:56:49,262 [8] DEBUG ApplicationLogger [(null)] - PoController无参数构造函数初始化！
2018-03-02 18:45:50,378 [1] DEBUG ApplicationLogger [(null)] - 日志服务开启成功！
2018-03-02 18:46:43,386 [11] DEBUG ApplicationLogger [(null)] - PoController无参数构造函数初始化！
2018-03-04 08:16:30,850 [1] DEBUG ApplicationLogger [(null)] - 日志服务开启成功！
2018-03-13 19:07:58,050 [1] DEBUG ApplicationLogger [(null)] - 日志服务开启成功！
2019-01-22 10:42:38,205 [1] DEBUG ApplicationLogger [(null)] - 日志服务开启成功！
2019-01-22 10:51:00,966 [10] DEBUG ApplicationLogger [(null)] - PoController无参数构造函数初始化！
2019-01-22 11:21:35,760 [1] DEBUG ApplicationLogger [(null)] - 日志服务开启成功！
2019-01-22 11:23:28,105 [1] DEBUG ApplicationLogger [(null)] - 日志服务开启成功！
2019-01-22 11:23:28,402 [45] ERROR ApplicationLogger [(null)] - 执行请求时出现异常！错误信息：未能找到路径“C:\Program Files (x86)\IIS Express\Dwonload\123.docx”的一部分。，请求参数：
System.IO.DirectoryNotFoundException: 未能找到路径“C:\Program Files (x86)\IIS Express\Dwonload\123.docx”的一部分。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   在 System.IO.FileStream..ctor(String path, FileMode mode)
   在 WebApi.Controllers.Download.DwonloadController.download() 位置 E:\study\后端学习\WebApi\Trunk\WebApi\Controllers\Download\DwonloadController.cs:行号 32
   在 System.Threading.Tasks.Task`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2019-01-22 11:27:16,494 [1] DEBUG ApplicationLogger [(null)] - 日志服务开启成功！
2019-01-22 11:29:53,467 [40] ERROR ApplicationLogger [(null)] - 执行请求时出现异常！错误信息：文件“E:\study\后端学习\WebApi\Trunk\WebApi\Dwonload\123.docx”正由另一进程使用，因此该进程无法访问此文件。，请求参数：
System.IO.IOException: 文件“E:\study\后端学习\WebApi\Trunk\WebApi\Dwonload\123.docx”正由另一进程使用，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   在 System.IO.FileStream..ctor(String path, FileMode mode)
   在 WebApi.Controllers.Download.DwonloadController.download() 位置 E:\study\后端学习\WebApi\Trunk\WebApi\Controllers\Download\DwonloadController.cs:行号 32
   在 System.Threading.Tasks.Task`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2019-01-22 11:30:31,868 [1] DEBUG ApplicationLogger [(null)] - 日志服务开启成功！
2019-01-22 12:53:21,740 [74] DEBUG ApplicationLogger [(null)] - 日志服务开启成功！
2019-01-22 12:53:37,243 [78] ERROR ApplicationLogger [(null)] - 执行请求时出现异常！错误信息：文件Dwonload\123.docx不存在！，请求参数：
System.Exception: 文件Dwonload\123.docx不存在！
   在 WebApi.Controllers.Download.BaseDwonloadEntity..ctor(String FilePath) 位置 E:\study\后端学习\WebApi\Trunk\WebApi\Controllers\Download\DownloadController.cs:行号 82
   在 WebApi.Controllers.Download.DownloadFileEntity..ctor(String FilePath) 位置 E:\study\后端学习\WebApi\Trunk\WebApi\Controllers\Download\DownloadController.cs:行号 123
   在 WebApi.Controllers.Download.DownloadController.DownloadFile(String filePath) 位置 E:\study\后端学习\WebApi\Trunk\WebApi\Controllers\Download\DownloadController.cs:行号 29
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2019-01-22 12:55:48,778 [74] DEBUG ApplicationLogger [(null)] - 日志服务开启成功！
2019-01-22 14:06:28,182 [12] DEBUG ApplicationLogger [(null)] - 日志服务开启成功！
2019-01-22 14:06:35,228 [24] ERROR ApplicationLogger [(null)] - 执行请求时出现异常！错误信息：已取消一个任务。，请求参数：
System.Threading.Tasks.TaskCanceledException: 已取消一个任务。
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2019-01-22 14:13:54,613 [19] DEBUG ApplicationLogger [(null)] - 日志服务开启成功！
2019-01-22 14:31:04,881 [19] DEBUG ApplicationLogger [(null)] - 日志服务开启成功！
2019-01-22 15:04:00,104 [15] DEBUG ApplicationLogger [(null)] - 日志服务开启成功！
2019-01-22 15:30:39,510 [15] DEBUG ApplicationLogger [(null)] - 日志服务开启成功！
2019-01-22 15:35:37,115 [1] DEBUG ApplicationLogger [(null)] - 日志服务开启成功！
2019-01-22 15:47:48,475 [1] DEBUG ApplicationLogger [(null)] - 日志服务开启成功！
2019-01-22 15:49:55,390 [13] ERROR ApplicationLogger [(null)] - 执行请求时出现异常！错误信息：值不能为 null。
参数名: path2，请求参数：
System.ArgumentNullException: 值不能为 null。
参数名: path2
   在 System.IO.Path.Combine(String path1, String path2)
   在 WebApi.Controllers.Download.DownloadController.DownloadVideo(String filePath) 位置 E:\study\后端学习\WebApi\Trunk\WebApi\Controllers\Download\DownloadController.cs:行号 47
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2019-01-22 15:49:56,318 [9] ERROR ApplicationLogger [(null)] - 执行请求时出现异常！错误信息：值不能为 null。
参数名: path2，请求参数：
System.ArgumentNullException: 值不能为 null。
参数名: path2
   在 System.IO.Path.Combine(String path1, String path2)
   在 WebApi.Controllers.Download.DownloadController.DownloadVideo(String filePath) 位置 E:\study\后端学习\WebApi\Trunk\WebApi\Controllers\Download\DownloadController.cs:行号 47
   在 lambda_method(Closure , Object , Object[] )
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
